### ISSUE TITLE
Music very loud - Option to turn it down?

### ISSUE THREAD

**Issue by Purenoiz** [NaorNC/nc-loadingscreens#3]
Hello, ive tried changing the settings, but i cant turn the music down. Not sure if there is a setting somewhere. thanks

**Comment by NaorNC** [comment]
Discord.gg/NCHub

**Comment by Purenoiz** [comment]
So i ask a question, you just put a link to your discord. I put two tickets in and ask the same question, but both tickets are deleted. How do i get an answer?
