### ISSUE TITLE
Missing Client Script Lua

### ISSUE THREAD

**Issue by WolfpackChloe** [NaorNC/nc-loadingscreens#8]
Missing script 'client.lua'

<img width="287" alt="Screenshot 2023-12-14 133758" src="https://github.com/NaorNC/nc-loadingscreens/assets/58238399/af7e2c79-7946-436c-b0d8-a76272b31c2b">

<img width="519" alt="Screenshot 2023-12-14 134208" src="https://github.com/NaorNC/nc-loadingscreens/assets/58238399/43f532fd-2519-4fdb-aedc-c2f13b962ee2">

**Comment by TheOnly3aq** [comment]
ig just remove it in the fxmanifest, must have been a mistake.
