### ISSUE TITLE
Cannot copy social links

### ISSUE THREAD

**Issue by 90smisfit** [NaorNC/nc-loadingscreens#9]
When i go to copy links. It says link has but copied but doesn't actually go to clipboard. Any fix for this? am I configured wrong?
![image](https://github.com/NaorNC/nc-loadingscreens/assets/174028615/edbf901a-edb1-42c7-813c-51c212dbda4c)

**Comment by alien7gaming** [comment]
server IP doent work with me
any help

**Comment by NaorNC** [comment]
Hey there,
Anyone who needs help, we are available on the discord server 24/7 - https://discord.gg/NCHub
